### ISSUE TITLE
Unable to export gpio-23: Error: ENOENT, open '/sys/class/gpio/gpio23/direction' consumed by P8_13

### ISSUE THREAD

**Issue by hairyhenderson** [theoctal/octalbonescript#12]
I'm getting this weird error trying to use octalbonescript for the first time.

Here's my test program:

``` js
var b = require('octalbonescript')
var red = "P8_13"

b.pinMode(red, b.OUTPUT, function(err) {
  if (err) return console.error(err)
  console.log('pinMode returned %j', arguments)
})
```

And when I run it:

``` sh
$ sudo node foo.js 
{ value: false,
  err: 'Unable to export gpio-23: Error: ENOENT, open \'/sys/class/gpio/gpio23/direction\'\nconsumed by P8_13' }
```

I've got an LED plugged into P8_13 and it's worked in the past with bonescript (admittedly, months ago).

This is with `octalbonescript@0.4.11` on Ubuntu 14.04.

``` sh
$ uname -a
Linux boron 3.8.13-bone30 #1 SMP Thu Nov 14 06:23:24 UTC 2013 armv7l armv7l armv7l GNU/Linux
$ dtc --version
Version: DTC 1.4.0-gf345d9e4
$ node -v
v0.10.33
```

Any ideas? Am I forgetting something basic? Doing something dumb? :)

**Comment by adityapatadia** [comment]
Glad that it worked. Let me know if you face any other issue.
