### ISSUE TITLE
Add support for promises 

### ISSUE THREAD

**Issue by adityapatadia** [theoctal/octalbonescript#17]
Implement nodejs promises using https://www.npmjs.com/package/q library. Users can write readable code and advantages of promise can be leveraged.

**Comment by Andrewiski** [comment]
@adityapatadia Please explain on how you were thinking of implementing promise support

also there is also a need for sync calls and I would suggest using fibers for that.

**Comment by adityapatadia** [comment]
Most functions have sync calls available. Please refer to wiki. I haven't thought much about promise support. It would be great if you can help.

**Comment by adityapatadia** [comment]
This library is abandoned. Please check notice in README for further information.
