### ISSUE TITLE
require('octalbonescript'); takes longer than require('bonescript');

### ISSUE THREAD

**Issue by TechplexEngineer** [theoctal/octalbonescript#28]
N matter the order OBS takes longer when required than BS. I wonder if there is a way to optimize the startup of the library.
**Results**
OBS: 2583ms
BS: 1515ms
_: 427ms
**Test Script**
```
console.time('OBS');
var b = require('octalbonescript');
console.timeEnd('OBS');

console.time('BS');
var b2 = require('bonescript');
console.timeEnd('BS');
```

**Comment by adityapatadia** [comment]
OBS loads 2 capes at start. One is universal cape and other is analog input cape. This ensures faster operations when doing pinMode so this pattern is preferred. I hope the time taken a beginning should not be much issue for you.

**Comment by TechplexEngineer** [comment]
Ah I understand. Shouldn't be too much trouble.
