### ISSUE TITLE
digitalWrite not sticky (doesn't hold state after program exits)

### ISSUE THREAD

**Issue by TechplexEngineer** [theoctal/octalbonescript#30]
I've found that analog writes are sticky (the pwm continutes to be generated after the program quits) however digitalWrites are not sticky, after the program quits they go back to their former state.

Test program:
```javascript
var pin = 'P8_10';

var b = require('octalbonescript');

b.pinMode(pin, b.OUTPUT, function(x) {
	console.log(x);
});
b.digitalWrite(pin, b.HIGH, function(x) {
	console.log(x);
});
```

To reproduce, watch the output of P8_10 on a scope or with a meter to see the change when the program exits.

**Comment by adityapatadia** [comment]
You can write code like this

```JavaScript

var pin = 'P8_10';

var b = require('octalbonescript');

b.pinMode(pin, b.OUTPUT, function(x) {
    b.digitalWrite(pin, b.HIGH, function(x) {
        console.log(x);
    });
});

```

**Comment by TechplexEngineer** [comment]
Ah, that makes sense. The Async nature of the calls lead to the pinMode occurring after the digital write I presume.

**Comment by adityapatadia** [comment]
Yup, that's the case :)
