### ISSUE TITLE
getPinMode broken

### ISSUE THREAD

**Issue by TechplexEngineer** [theoctal/octalbonescript#33]
It seems that getPinMode is broken.
Running the following code prints `null`

```javascript
var b = require('octalbonescript');
b.getPinMode("P9_14", printPinMux);
function printPinMux(x) {
    console.log(x);
}
```

**Comment by TechplexEngineer** [comment]
After digging into the code I realized that the callback takes two parameters, err then data.

working example 
```javascript
var b = require('octalbonescript');
b.getPinMode("P9_14", printPinMux);
function printPinMux(err, data) {
    console.log(err, data);
}
```

**Comment by adityapatadia** [comment]
Yes, v1.0.0 changes callback pattern and every callback has now two parameters, err and data. We need to properly document it before making a release.
