### ISSUE TITLE
how to use pins assigned to LCD

### ISSUE THREAD

**Issue by TechplexEngineer** [theoctal/octalbonescript#34]
Looking at the following image one gets the impression that there aren't many GPIO's available. However if one does not have an LCD there should be a bunch more GPIO's available. Namely P8_27-P8_46. However trying to access these pins with OBS seems not to work. Is there something that needs to be done to activate them?

![](http://beagleboard.org/static/images/cape-headers.png)

**Comment by adityapatadia** [comment]
No need to activate anything. You can just disable HDMI cape and then doing pinMode on those pins should just work fine. If you face any problems, you can post debug output here.
