### ISSUE TITLE
Cannot find module 'octalbonescript'

### ISSUE THREAD

**Issue by ercint** [theoctal/octalbonescript#43]
Hi,

I used octalbonescript to catch interrupts and write GPIO outputs, mostly simple actions actually. 

When I tried to install my project as a service, I can successfully install it, but when I restart my BBB, my project does not start at boot and gives "Cannot find module 'octalbonescript" error.

But I can start my project by myself in shell command line.

Do you have an idea about that? Where can I define octalbone script into service?

Note: I installed octalbone script globally.

**Comment by adityapatadia** [comment]
I would suggest you use https://github.com/Unitech/pm2 to start your scripts on reboot. It is better solution which I personally use in my projects.
