### ISSUE TITLE
missing callback causes crash

### ISSUE THREAD

**Issue by bigmonkeyboy** [theoctal/octalbonescript#51]
I know the new style is to use callbacks for everything... but... if the callback is missing then the script errors out...

eg calling digital write with just a pin and value causes

    Uncaught Exception:
    TypeError: undefined is not a function
    at onWriteGPIO (/root/node_modules/octalbonescript/lib/digital.js:185:17)
    ....

which comes from a `callback(null);`  where of course callback itself is not defined...
Ideally I think you should allow the user not to have to define a callback... if they don't want to.

**Comment by adityapatadia** [comment]
This I will fix this in new version. It’s indeed a bug. Please list which functions throw this error.

**Comment by bigmonkeyboy** [comment]
Hi - a quick `grep -rn "    callback" ` in the lib directory would seem to indicate that there are quite a few places - some of which may be handled by a surrounding if block... but many are not.

**Comment by adityapatadia** [comment]
:) sure. I will get them fixed.

**Comment by bigmonkeyboy** [comment]
Yes - much better... Thanks !
