### ISSUE TITLE
Having an issue loading the library with Node 4.4.7

### ISSUE THREAD

**Issue by mbush92** [theoctal/octalbonescript#70]
I am running a Beagle Bone variant which is running node 4.4.7 and I am having issues getting the library to install using `npm install octalbonescript`  Are there any known limitations to running the library with a newer version of node?  I am running Debian kernel 3.8.13-bone70

**Comment by adityapatadia** [comment]
Can you post output? I want to check the failure message.

**Comment by adityapatadia** [comment]
Closing this for now. I will re-open if you can give more information.
