### ISSUE TITLE
SPI Support in the Octal Bone Script Library?

### ISSUE THREAD

**Issue by totem415** [theoctal/octalbonescript#72]
Any thoughts on how my project should do SPI communication?  I'm worried that 3rd party node modules would conflict since they are accessing pins to communicate.  Any help or suggestions would be greatly appreciated.

BTW the OBS is working great for our needs so far.  Thanks so much for developing and maintaining!

-roger

**Comment by adityapatadia** [comment]
I don't think SPI is currently possible with code as is. You should find a device tree and load it to work on it. https://github.com/beagleboard/bb.org-overlays/tree/master/src/arm

I am afraid lot of code changes needs to be done to support this and I currently don't have time to work on it. If you are willing to do, please create PR.

**Comment by adityapatadia** [comment]
This library is abandoned. Please check notice in README for further information.
